// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjG2bvfNfXnyQgK8Q88HR8w2bnekD0f_E',
    appId: '1:1017605429774:android:454264fffead990c70ba5f',
    messagingSenderId: '1017605429774',
    projectId: 'flutter-ebook-a',
    databaseURL: 'https://flutter-ebook-a-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-ebook-a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCK7sunNqV6dUfswngY1ALs5IaxbEawNAY',
    appId: '1:1017605429774:ios:0345aa1137d7010770ba5f',
    messagingSenderId: '1017605429774',
    projectId: 'flutter-ebook-a',
    databaseURL: 'https://flutter-ebook-a-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-ebook-a.appspot.com',
    androidClientId: '1017605429774-1jgu12g8dpgcsvfkohi75e80j581nsfa.apps.googleusercontent.com',
    iosClientId: '1017605429774-rp4ov3kl3o1a0bfudjebem13c6ovrv7m.apps.googleusercontent.com',
    iosBundleId: 'com.example.ebookApplication',
  );
}
